server:
  port: 8088

spring:
  application:
    name: api-gateway
    
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.vvid}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true   #indica que la puerta de enlace habilita la función de registro y descubrimiento de servicios
      routes:
        - id: micro01
          uri: http://localhost:8085/
          predicates:
            - Path=/api/**