server:
  port: 8011

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true //indica que la puerta de enlace habilita la función de registro y descubrimiento de servicios
      routes:
        - id: micro01
          uri: lb://MICRO01
          predicates:
            - Path=/afiliado/**
        - id: micro02
          uri: lb://MICRO02
          predicates:
            - Path=/afp/**
        - id: micro03
          uri: http://localhost:8087/
          predicates:
            - Path=/poliza/**
