server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservicio01
          uri: lb://microservicio01
          predicates:
            - Path=/afiliado/**
        - id: microservicio02
          uri: lb://microservicio02
          predicates:
            - Path=/afp/**