server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #indica que la puerta de enlace habilita la función de registro y descubrimiento de servicios
      routes:
        - id: micro01
          uri: http://localhost:8085/
          predicates:
            - Path=/WebFluxConvertAmount/**
        - id: micro01
          uri: http://localhost:8085/
          predicates:
            - Path=/WebFluxExchangeRate/**