server:
  port: 8011

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #indica que la puerta de enlace habilita la función de registro y descubrimiento de servicios
      routes:
        - id: micro01
          uri: lb://MICRO01
          predicates:
            - Path=/exchangerate/**
